/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package parking;

import java.awt.Color;
import java.awt.Image;
import java.io.*;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author eddaf
 */
public class Fenetrepark extends javax.swing.JFrame {
    ArrayList<Vehicule> Vehicules;
    DefaultListModel modeleListe;
    File fichier;
    FileWriter fw;
    PrintWriter pw;
    /**
     * Creates new form Fenetrepark
     */
    public Fenetrepark() {
        initComponents();
        Vehicules = new ArrayList<>();
        modeleListe = new DefaultListModel();
        try {
            fichier = new File("fichier.veh");
            fw = new FileWriter(fichier); 
            pw = new PrintWriter(fw);
        } catch (IOException ex) {
           ex.printStackTrace();
        }
        //ajoute une icon 
        Image img = new ImageIcon(this.getClass().getResource("/parking1.png")).getImage();
        this.setIconImage(img);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listeVehicule = new javax.swing.JList<>();
        buttonSupprimer = new javax.swing.JButton();
        buttonAjouter = new javax.swing.JButton();
        buttonModifier = new javax.swing.JButton();
        buttonEnregister = new javax.swing.JButton();
        buttonFermer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        listeVehicule.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jScrollPane1.setViewportView(listeVehicule);

        buttonSupprimer.setBackground(new java.awt.Color(204, 204, 255));
        buttonSupprimer.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        buttonSupprimer.setText("Supprimer");
        buttonSupprimer.setSelected(true);
        buttonSupprimer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonSupprimerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonSupprimerMouseExited(evt);
            }
        });
        buttonSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSupprimerActionPerformed(evt);
            }
        });

        buttonAjouter.setBackground(new java.awt.Color(0, 204, 102));
        buttonAjouter.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        buttonAjouter.setText("Ajouter");
        buttonAjouter.setToolTipText("");
        buttonAjouter.setSelected(true);
        buttonAjouter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonAjouterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonAjouterMouseExited(evt);
            }
        });
        buttonAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAjouterActionPerformed(evt);
            }
        });

        buttonModifier.setBackground(new java.awt.Color(204, 204, 255));
        buttonModifier.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        buttonModifier.setText("Modifier");
        buttonModifier.setSelected(true);
        buttonModifier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonModifierMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonModifierMouseExited(evt);
            }
        });
        buttonModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonModifierActionPerformed(evt);
            }
        });

        buttonEnregister.setBackground(new java.awt.Color(204, 204, 255));
        buttonEnregister.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        buttonEnregister.setText("Enregister");
        buttonEnregister.setSelected(true);
        buttonEnregister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonEnregisterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonEnregisterMouseExited(evt);
            }
        });
        buttonEnregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEnregisterActionPerformed(evt);
            }
        });

        buttonFermer.setBackground(new java.awt.Color(255, 0, 51));
        buttonFermer.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 20)); // NOI18N
        buttonFermer.setForeground(new java.awt.Color(255, 255, 255));
        buttonFermer.setText("Fermer");
        buttonFermer.setSelected(true);
        buttonFermer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonFermerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonFermerMouseExited(evt);
            }
        });
        buttonFermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFermerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addComponent(buttonModifier, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(buttonEnregister)
                        .addGap(47, 47, 47)
                        .addComponent(buttonSupprimer)
                        .addGap(415, 415, 415)
                        .addComponent(buttonFermer)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonEnregister, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonFermer, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buttonAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buttonModifier, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buttonSupprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSupprimerActionPerformed
        if(listeVehicule.isSelectionEmpty()){
            JOptionPane.showConfirmDialog(this, "Selectionner un vehicule a supprimer", "Selectionnment",JOptionPane.ERROR_MESSAGE);
        }
        else{
            int indice = listeVehicule.getSelectedIndex();
            modeleListe.remove(indice);
            Vehicules.remove(indice); 
        }
    }//GEN-LAST:event_buttonSupprimerActionPerformed

    private void buttonEnregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEnregisterActionPerformed
        for(Vehicule v:Vehicules){
            pw.println(v);
        }
        pw.close();  
    }//GEN-LAST:event_buttonEnregisterActionPerformed

    private void buttonFermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFermerActionPerformed
        // TODO add your handling code here:
        int choix = JOptionPane.showConfirmDialog(this, "Voulez-vous vraiment quitter cette page ?", "Confirmation !!", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(choix==0){
            System.exit(0);
        }
    }//GEN-LAST:event_buttonFermerActionPerformed

    private void buttonAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAjouterActionPerformed
        Vehicule vehicule = null;
        String type,marque,modele,immatriculation;
        int NumPorte,vitersseMax,choix = 0;
        boolean remorque;
        type = marque = JOptionPane.showInputDialog(this,"Entrez le type de vehicule Voiture/Camion/Moto : ",
                "type", JOptionPane.PLAIN_MESSAGE);
        if (type==null){
            
        }
        else if(type.equalsIgnoreCase("voiture")){
            marque = JOptionPane.showInputDialog(this,"Entrez la marque de vehicule: ",
                    "marque", JOptionPane.PLAIN_MESSAGE);
            modele = JOptionPane.showInputDialog(this,"Entrez le modele de vehicule: ",
                    "modele", JOptionPane.PLAIN_MESSAGE);
            immatriculation = JOptionPane.showInputDialog(this,"Entrez l'immatriculation de vehicule: ",
                    "immatriculation", JOptionPane.PLAIN_MESSAGE);
            NumPorte = Integer.parseInt(JOptionPane.showInputDialog(this,"Entrez le nomber de portes",
                    "nomber de portes ", JOptionPane.PLAIN_MESSAGE));
            vehicule = new Voiture(marque, modele, immatriculation, NumPorte);
        }
        else if (type.equalsIgnoreCase("Moto")){
            marque = JOptionPane.showInputDialog(this,"Entrez la marque de vehicule: ",
                    "marque", JOptionPane.PLAIN_MESSAGE);
            modele = JOptionPane.showInputDialog(this,"Entrez le modele de vehicule: ",
                    "modele", JOptionPane.PLAIN_MESSAGE);
            immatriculation = JOptionPane.showInputDialog(this,"Entrez l'immatriculation de vehicule: ",
                    "immatriculation", JOptionPane.PLAIN_MESSAGE);
            vitersseMax = Integer.parseInt(JOptionPane.showInputDialog(this,"Entrez la vitesse maximale de Moto: ",
                    "vitesse max", JOptionPane.PLAIN_MESSAGE));
            vehicule = new Moto(marque, modele, immatriculation, vitersseMax);
        }
        else if(type.equalsIgnoreCase("Camion")){ 
            marque = JOptionPane.showInputDialog(this,"Entrez la marque de vehicule: ",
                    "marque", JOptionPane.PLAIN_MESSAGE);
            modele = JOptionPane.showInputDialog(this,"Entrez le modele de vehicule: ",
                    "modele", JOptionPane.PLAIN_MESSAGE);
            immatriculation = JOptionPane.showInputDialog(this,"Entrez l'immatriculation de vehicule: ",
                    "immatriculation", JOptionPane.PLAIN_MESSAGE);
            choix = JOptionPane.showConfirmDialog(this, "le camion a un remorque ou non?", "remorque", JOptionPane.YES_NO_OPTION);
            if(choix == 0)remorque=true;
            else remorque=false;
            vehicule = new Camion(marque, modele, immatriculation, remorque);
        }
        else{
            JOptionPane.showConfirmDialog(this, "Votre choix et incorrecte",
                    "choix incorrect", JOptionPane.OK_OPTION);
        }
        Vehicules.add(vehicule);
        modeleListe.add(modeleListe.getSize(), vehicule);
        listeVehicule.setModel(modeleListe);

    }//GEN-LAST:event_buttonAjouterActionPerformed

    private void buttonModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonModifierActionPerformed
        // TODO add your handling code here:
        String marque,modele,immatriculation;
        int NumPorte,vitesseMax,remorque;
        if(listeVehicule.isSelectionEmpty()){
            JOptionPane.showConfirmDialog(this, "Selectionner un vehicule a Modifier",
                    "Selectionnment",JOptionPane.ERROR_MESSAGE);
        }
        else{
            int indice = listeVehicule.getSelectedIndex();
            Vehicule v = Vehicules.get(indice);
            marque = JOptionPane.showInputDialog(this, "changez la marque",
                    v.getMarque());
            v.setMarque(marque);
            modele = JOptionPane.showInputDialog(this, "changez le modele",
                    v.getModele());
            v.setModele(modele);
            immatriculation = JOptionPane.showInputDialog(this, "changez l'immatriculation",
                    v.getImmatriculation());
            v.setImmatriculation(immatriculation);
            if(v instanceof Voiture){
                NumPorte =Integer.parseInt( JOptionPane.showInputDialog(this, "changez le nomber de porte","Numero de porte",
                        ((Voiture) v).getNumPorte()));
            }
            else if (v instanceof Camion){
                remorque = JOptionPane.showConfirmDialog(this, "Le camion a un remorque", "Remorque", JOptionPane.ERROR_MESSAGE);
                boolean choix = true;
                if(remorque==JOptionPane.NO_OPTION)choix=false;
                    ((Camion) v).setRemorque(choix);
            }
            else if (v instanceof Moto){
                vitesseMax = Integer.parseInt( JOptionPane.showInputDialog(this, "changez la vitesse Maximale","vitesse maximale",((Moto) v).getVitesseMax()));
            }
            else{
                JOptionPane.showMessageDialog(this, "Erreur Inconnue","Erreur",JOptionPane.ERROR_MESSAGE);
            }
            listeVehicule.setModel(modeleListe);
        }
    }//GEN-LAST:event_buttonModifierActionPerformed
//entre pour changer dans le coleur de du buttom
    //**
    private void buttonAjouterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAjouterMouseEntered
        buttonAjouter.setBackground(new Color(0,204,0));
        
    }//GEN-LAST:event_buttonAjouterMouseEntered

    private void buttonModifierMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonModifierMouseEntered
        buttonModifier.setBackground(new Color(153,153,255));
    }//GEN-LAST:event_buttonModifierMouseEntered

    private void buttonEnregisterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonEnregisterMouseEntered
        buttonEnregister.setBackground(new Color(153,153,255));
    }//GEN-LAST:event_buttonEnregisterMouseEntered

    private void buttonSupprimerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSupprimerMouseEntered
        buttonSupprimer.setBackground(new Color(153,153,255));
    }//GEN-LAST:event_buttonSupprimerMouseEntered

    private void buttonFermerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonFermerMouseEntered
        buttonFermer.setBackground(new Color(255,102,102));
    }//GEN-LAST:event_buttonFermerMouseEntered

    private void buttonModifierMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonModifierMouseExited
        buttonModifier.setBackground(new Color(204,204,255));
    }//GEN-LAST:event_buttonModifierMouseExited

    private void buttonEnregisterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonEnregisterMouseExited
        buttonEnregister.setBackground(new Color(204,204,255));
    }//GEN-LAST:event_buttonEnregisterMouseExited

    private void buttonSupprimerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSupprimerMouseExited
        buttonSupprimer.setBackground(new Color(204,204,255));
    }//GEN-LAST:event_buttonSupprimerMouseExited

    private void buttonAjouterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAjouterMouseExited
        buttonAjouter.setBackground(new Color(0,204,102));
    }//GEN-LAST:event_buttonAjouterMouseExited

    private void buttonFermerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonFermerMouseExited
        buttonFermer.setBackground(new Color(255,0,51));
    }//GEN-LAST:event_buttonFermerMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fenetrepark.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fenetrepark.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fenetrepark.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fenetrepark.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               Fenetrepark  f = new Fenetrepark();
               f.setVisible(true);
               f.setTitle("Gestion de Parking");
               f.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAjouter;
    private javax.swing.JButton buttonEnregister;
    private javax.swing.JButton buttonFermer;
    private javax.swing.JButton buttonModifier;
    private javax.swing.JButton buttonSupprimer;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listeVehicule;
    // End of variables declaration//GEN-END:variables

}